export const actionTypes = {
    SET_ALL_POKEMONS: "SET_ALL_POKEMONS",
    SET_SOLO_POKEMON: "SET_SOLO_POKEMON",
    SET_PAGES_COUNT: "SET_PAGES_COUNT",
    SET_SHOW_FILTERED_LIST: "SET_SHOW_FILTERED_LIST",
    SET_CURRENT_PAGE: "SET_CURRENT_PAGE",
    SET_PAGES_ARRAY: "SET_PAGES_ARRAY",
    SET_PAGE_NUMBER: "SET_PAGE_NUMBER"
}
